### ISSUE TITLE
Error in the Readme 

### ISSUE THREAD

**Issue by BoneofMalkav** [LordMisfit/NR-IotDM#1]
"Installing 2. - Unzip the contents of the NR-IotDM-master.zip into the folder you made above. Don't put the files in their own directory, since a proper version of EDuke32.exe is packaged with this."

Except eduke32.exe isn't contained in the download.

**Comment by LordMisfit** [comment]
It was originally taken out and I forgot to remove the rule, but I've added a new version in now. :V
